// a2aq-codegen — AgentCard skills → a typed invocation module (the mcpq
// codegen pattern, output target per the orval / connect-query precedent:
// typed HOOKS over a framework-free send layer).
//
// WHAT THE CARD ACTUALLY PROVIDES: A2A's AgentSkill declares id, name,
// description, tags, examples and media modes (inputModes/outputModes) —
// it does NOT carry parameter schemas (no JSON Schema, nothing to derive
// typed params from). So the generated helpers are honest: every skill
// accepts `SkillInput` (string | Part[]), the skill id travels in message
// metadata (see SKILL_METADATA_KEY), and the card's modes/examples are
// surfaced as JSDoc where a schema would otherwise inform the types.

import type { AgentCard, AgentSkill } from "@a2a-js/sdk";

export interface GenerateSkillModuleOptions {
  /** Also emit a `useX` hook per skill (adds an import from the react subpath). Default false. */
  hooks?: boolean;
  /** Module specifier the send layer is imported from. Default `"@johnhenry/a2aq"`. */
  importFrom?: string;
  /** Module specifier the hook layer is imported from. Default `"@johnhenry/a2aq/react"`. */
  reactImportFrom?: string;
}

/** PascalCase a skill id into an identifier fragment (`book-flight` → `BookFlight`). */
function pascal(id: string): string {
  const segments = id.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const joined = segments.map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join("");
  return joined || "Skill";
}

/** JSDoc-safe text: keep it one-line, close no comments early. */
const doc = (s: string): string => s.replace(/\s+/g, " ").replaceAll("*/", "*\\/").trim();

const quote = (s: string): string => JSON.stringify(s);

/**
 * Generate the TypeScript source of a skill-invocation module for a card:
 * per skill a typed `sendX(q, agent, input, opts?)` helper (and, with
 * `hooks`, a `useX(q, agent)` hook over `useSkillTask`), plus a `skills`
 * record and a `SkillId` union for UI listings. Deterministic output —
 * suitable for golden files and check-in.
 */
export function generateSkillModule(card: AgentCard, opts: GenerateSkillModuleOptions = {}): string {
  const importFrom = opts.importFrom ?? "@johnhenry/a2aq";
  const reactImportFrom = opts.reactImportFrom ?? "@johnhenry/a2aq/react";
  const skills: AgentSkill[] = card.skills ?? [];

  // Collision-proof identifiers: first-come keeps the clean name.
  const used = new Set<string>();
  const ident = (skill: AgentSkill): string => {
    let base = pascal(skill.id);
    let name = base;
    for (let n = 2; used.has(name); n++) name = `${base}${n}`;
    used.add(name);
    return name;
  };
  const named = skills.map((skill) => ({ skill, name: ident(skill) }));

  const lines: string[] = [];
  lines.push(`// Generated by a2aq-codegen — DO NOT EDIT.`);
  lines.push(`// Agent: ${doc(card.name)} (v${doc(card.version)})`);
  if (card.description) lines.push(`// ${doc(card.description)}`);
  lines.push(`//`);
  lines.push(`// A2A AgentSkill declares media modes, tags and examples — NOT parameter`);
  lines.push(`// schemas. There is nothing in the card to derive typed params from, so`);
  lines.push(`// every helper takes SkillInput (string | Part[]); the skill id travels in`);
  lines.push(`// message metadata under the SKILL_METADATA_KEY ("a2aq/skillId").`);
  lines.push(``);
  if (named.length > 0) {
    lines.push(`import { sendSkill, type A2AQuery, type SkillInput, type SkillSendOptions, type TaskHandle } from ${quote(importFrom)};`);
    if (opts.hooks) {
      lines.push(`import { useSkillTask, type UseSkillTaskResult } from ${quote(reactImportFrom)};`);
    }
    lines.push(`import type { Message } from "@a2a-js/sdk";`);
    lines.push(``);
  }
  lines.push(`/** Every skill the card declares, by id — discovery data for UI listings. */`);
  lines.push(`export const skills = {`);
  for (const { skill } of named) {
    lines.push(`  ${quote(skill.id)}: {`);
    lines.push(`    id: ${quote(skill.id)},`);
    lines.push(`    name: ${quote(skill.name)},`);
    lines.push(`    description: ${quote(skill.description)},`);
    lines.push(`    tags: ${JSON.stringify(skill.tags ?? [])},`);
    lines.push(`    examples: ${JSON.stringify(skill.examples ?? [])},`);
    lines.push(`    inputModes: ${JSON.stringify(skill.inputModes ?? [])},`);
    lines.push(`    outputModes: ${JSON.stringify(skill.outputModes ?? [])},`);
    lines.push(`  },`);
  }
  lines.push(`} as const;`);
  lines.push(``);
  lines.push(`export type SkillId = keyof typeof skills;`);

  for (const { skill, name } of named) {
    const input = (skill.inputModes ?? []).join(", ") || "(agent defaults)";
    const output = (skill.outputModes ?? []).join(", ") || "(agent defaults)";
    lines.push(``);
    lines.push(`/**`);
    lines.push(` * ${doc(skill.name)} — ${doc(skill.description) || "(no description)"}`);
    lines.push(` *`);
    lines.push(` * input: ${doc(input)} · output: ${doc(output)}`);
    for (const ex of skill.examples ?? []) lines.push(` * e.g. ${doc(ex)}`);
    lines.push(` */`);
    lines.push(`export function send${name}(`);
    lines.push(`  q: A2AQuery,`);
    lines.push(`  agent: string,`);
    lines.push(`  input: SkillInput,`);
    lines.push(`  opts?: SkillSendOptions,`);
    lines.push(`): Promise<Message | TaskHandle> {`);
    lines.push(`  return sendSkill(q, agent, ${quote(skill.id)}, input, opts);`);
    lines.push(`}`);
    if (opts.hooks) {
      lines.push(``);
      lines.push(`/** ${doc(skill.name)} as a mutation-shaped hook (see useSkillTask). */`);
      lines.push(`export function use${name}(q: A2AQuery, agent: string): UseSkillTaskResult {`);
      lines.push(`  return useSkillTask(q, agent, ${quote(skill.id)});`);
      lines.push(`}`);
    }
  }
  lines.push(``);
  return lines.join("\n");
}
